modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="medieval_adventures"
version="1.0.0"
displayName="Medieval Adventures"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Alessandro, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.medieval_adventures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



